stages:
  - build

build:
  stage: build
  variables:
    VERSION: '$CI_PIPELINE_ID.0'
    MODULE_CODE: 'CORE'
  script:
    - 'echo %CI_PROJECT_DIR%'
    - 'call C:\Builds\test\set.bat %CI_PROJECT_DIR% %CI_PROJECT_NAMESPACE% %CI_PROJECT_NAME% %CI_PIPELINE_ID% %CI_COMMIT_SHA% %MODULE_CODE%'
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe" /t:restore %CI_PROJECT_NAMESPACE%.%CI_PROJECT_NAME%.sln /p:RestoreConfigFile=C:\Builds\test\NuGet.Config /p:Configuration="Release"'
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe" %CI_PROJECT_NAMESPACE%.%CI_PROJECT_NAME%.sln /m /tv:15.0 /p:DoEvents=false /p:Configuration="Release" /p:Platform="Any Cpu"'
    - 'call C:\Builds\test\pack_and_tag.bat %CI_PROJECT_DIR% %CI_PROJECT_NAMESPACE% %CI_PROJECT_NAME% %CI_PIPELINE_ID% %CI_COMMIT_SHA% %MODULE_CODE% %CI_COMMIT_REF_NAME% %CI_PROJECT_PATH%' 
  tags:
    - msbuild