name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12.x
    - name: Install Packages
      run: npm install
    - name: Check Commit Message
      run: | 
        echo "${{github.event.head_commit.message}}" > commit.msg
        cat commit.msg | npx commitlint -g commitlint.config.js
        rm commit.msg
    - name: "Get Next Version"
      id: semver
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: "${{ github.token }}"
        dry_run: true
    - name: Set .Net Version
      uses: cdotyone/github-set-net-version@master
      id: cleaned
      with:
        version: "${{ steps.semver.outputs.new_version }}"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '2.2.108'
    - name: Install Nuget Dependencies
      run: dotnet restore
    - name: Build .NET
      run: dotnet pack --configuration Release --no-restore -p:PackageVersion=${{ steps.cleaned.outputs.version }} --output dist 
    - name: Publish Nuget Package
      run: dotnet nuget push dist\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_KEY }}
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ github.token }}
        tag-prefix: 'v'
        release-count: '20'
    - name: Push
      uses: cdotyone/github-push@master
      with:
        version: "${{ steps.cleaned.outputs.version }}"
      env:
        GITHUB_TOKEN: "${{ github.token }}"